// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: api/task.proto

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyDate) Reset() {
	*x = MyDate{}
	mi := &file_api_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyDate) ProtoMessage() {}

func (x *MyDate) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyDate.ProtoReflect.Descriptor instead.
func (*MyDate) Descriptor() ([]byte, []int) {
	return file_api_task_proto_rawDescGZIP(), []int{0}
}

func (x *MyDate) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *MyDate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *MyDate) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Unique ID number for this person.
	Date          *MyDate                `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetDate() *MyDate {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Task) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_api_task_proto protoreflect.FileDescriptor

const file_api_task_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/task.proto\x12\x04task\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x06MyDate\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\"\x8e\x01\n" +
	"\x04Task\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\x04date\x18\x03 \x01(\v2\f.task.MyDateR\x04date\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04timeB(Z&tgBot/bot-service/protoGenFiles/taskpbb\x06proto3"

var (
	file_api_task_proto_rawDescOnce sync.Once
	file_api_task_proto_rawDescData []byte
)

func file_api_task_proto_rawDescGZIP() []byte {
	file_api_task_proto_rawDescOnce.Do(func() {
		file_api_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_proto_rawDesc), len(file_api_task_proto_rawDesc)))
	})
	return file_api_task_proto_rawDescData
}

var file_api_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_task_proto_goTypes = []any{
	(*MyDate)(nil),                // 0: task.MyDate
	(*Task)(nil),                  // 1: task.Task
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_task_proto_depIdxs = []int32{
	0, // 0: task.Task.date:type_name -> task.MyDate
	2, // 1: task.Task.time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_task_proto_init() }
func file_api_task_proto_init() {
	if File_api_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_proto_rawDesc), len(file_api_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_task_proto_goTypes,
		DependencyIndexes: file_api_task_proto_depIdxs,
		MessageInfos:      file_api_task_proto_msgTypes,
	}.Build()
	File_api_task_proto = out.File
	file_api_task_proto_goTypes = nil
	file_api_task_proto_depIdxs = nil
}
