// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: api/task_service.proto

package taskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskResponse) Reset() {
	*x = SendTaskResponse{}
	mi := &file_api_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskResponse) ProtoMessage() {}

func (x *SendTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskResponse.ProtoReflect.Descriptor instead.
func (*SendTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_task_service_proto protoreflect.FileDescriptor

const file_api_task_service_proto_rawDesc = "" +
	"\n" +
	"\x16api/task_service.proto\x12\x04task\x1a\x0eapi/task.proto\"\"\n" +
	"\x10SendTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2=\n" +
	"\vTaskService\x12.\n" +
	"\bSendTask\x12\n" +
	".task.Task\x1a\x16.task.SendTaskResponseB(Z&tgBot/bot-service/protoGenFiles/taskpbb\x06proto3"

var (
	file_api_task_service_proto_rawDescOnce sync.Once
	file_api_task_service_proto_rawDescData []byte
)

func file_api_task_service_proto_rawDescGZIP() []byte {
	file_api_task_service_proto_rawDescOnce.Do(func() {
		file_api_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_task_service_proto_rawDesc), len(file_api_task_service_proto_rawDesc)))
	})
	return file_api_task_service_proto_rawDescData
}

var file_api_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_task_service_proto_goTypes = []any{
	(*SendTaskResponse)(nil), // 0: task.SendTaskResponse
	(*Task)(nil),             // 1: task.Task
}
var file_api_task_service_proto_depIdxs = []int32{
	1, // 0: task.TaskService.SendTask:input_type -> task.Task
	0, // 1: task.TaskService.SendTask:output_type -> task.SendTaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_task_service_proto_init() }
func file_api_task_service_proto_init() {
	if File_api_task_service_proto != nil {
		return
	}
	file_api_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_task_service_proto_rawDesc), len(file_api_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_task_service_proto_goTypes,
		DependencyIndexes: file_api_task_service_proto_depIdxs,
		MessageInfos:      file_api_task_service_proto_msgTypes,
	}.Build()
	File_api_task_service_proto = out.File
	file_api_task_service_proto_goTypes = nil
	file_api_task_service_proto_depIdxs = nil
}
