// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: task_service.proto

package taskpb

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendTask
type SendTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskRequest) Reset() {
	*x = SendTaskRequest{}
	mi := &file_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskRequest) ProtoMessage() {}

func (x *SendTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskRequest.ProtoReflect.Descriptor instead.
func (*SendTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *SendTaskRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type SendTaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UserErrorMessage string                 `protobuf:"bytes,2,opt,name=userErrorMessage,proto3" json:"userErrorMessage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendTaskResponse) Reset() {
	*x = SendTaskResponse{}
	mi := &file_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskResponse) ProtoMessage() {}

func (x *SendTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskResponse.ProtoReflect.Descriptor instead.
func (*SendTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendTaskResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SendTaskResponse) GetUserErrorMessage() string {
	if x != nil {
		return x.UserErrorMessage
	}
	return ""
}

// GetTasks
type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Task          []*Task                `protobuf:"bytes,2,rep,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetTasksResponse) GetTask() []*Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// DeleteTask
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	TaskNumber    int64                  `protobuf:"varint,2,opt,name=taskNumber,proto3" json:"taskNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTaskRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *DeleteTaskRequest) GetTaskNumber() int64 {
	if x != nil {
		return x.TaskNumber
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        *status.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteTaskResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// ChangeTask
type ChangeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	TaskNum       int64                  `protobuf:"varint,2,opt,name=taskNum,proto3" json:"taskNum,omitempty"`
	NewValue      string                 `protobuf:"bytes,3,opt,name=newValue,proto3" json:"newValue,omitempty"`
	ChangeValue   string                 `protobuf:"bytes,4,opt,name=changeValue,proto3" json:"changeValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaskRequest) Reset() {
	*x = ChangeTaskRequest{}
	mi := &file_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaskRequest) ProtoMessage() {}

func (x *ChangeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaskRequest.ProtoReflect.Descriptor instead.
func (*ChangeTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeTaskRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ChangeTaskRequest) GetTaskNum() int64 {
	if x != nil {
		return x.TaskNum
	}
	return 0
}

func (x *ChangeTaskRequest) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *ChangeTaskRequest) GetChangeValue() string {
	if x != nil {
		return x.ChangeValue
	}
	return ""
}

type ChangeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        *status.Status         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTaskResponse) Reset() {
	*x = ChangeTaskResponse{}
	mi := &file_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTaskResponse) ProtoMessage() {}

func (x *ChangeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTaskResponse.ProtoReflect.Descriptor instead.
func (*ChangeTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChangeTaskResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_task_service_proto protoreflect.FileDescriptor

const file_task_service_proto_rawDesc = "" +
	"\n" +
	"\x12task_service.proto\x12\x04task\x1a\x17google/rpc/status.proto\x1a\n" +
	"task.proto\"M\n" +
	"\x0fSendTaskRequest\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".task.TaskR\x04task\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\"j\n" +
	"\x10SendTaskResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\x12*\n" +
	"\x10userErrorMessage\x18\x02 \x01(\tR\x10userErrorMessage\"-\n" +
	"\x0fGetTasksRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\"B\n" +
	"\x10GetTasksResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1e\n" +
	"\x04task\x18\x02 \x03(\v2\n" +
	".task.TaskR\x04task\"O\n" +
	"\x11DeleteTaskRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x1e\n" +
	"\n" +
	"taskNumber\x18\x02 \x01(\x03R\n" +
	"taskNumber\"P\n" +
	"\x12DeleteTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status\"\x87\x01\n" +
	"\x11ChangeTaskRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x18\n" +
	"\ataskNum\x18\x02 \x01(\x03R\ataskNum\x12\x1a\n" +
	"\bnewValue\x18\x03 \x01(\tR\bnewValue\x12 \n" +
	"\vchangeValue\x18\x04 \x01(\tR\vchangeValue\"P\n" +
	"\x12ChangeTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x12.google.rpc.StatusR\x06status2\x85\x02\n" +
	"\vTaskService\x129\n" +
	"\bSendTask\x12\x15.task.SendTaskRequest\x1a\x16.task.SendTaskResponse\x129\n" +
	"\bGetTasks\x12\x15.task.GetTasksRequest\x1a\x16.task.GetTasksResponse\x12?\n" +
	"\n" +
	"DeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x18.task.DeleteTaskResponse\x12?\n" +
	"\n" +
	"ChangeTask\x12\x17.task.ChangeTaskRequest\x1a\x18.task.ChangeTaskResponseB(Z&tgBot/bot-service/protoGenFiles/taskpbb\x06proto3"

var (
	file_task_service_proto_rawDescOnce sync.Once
	file_task_service_proto_rawDescData []byte
)

func file_task_service_proto_rawDescGZIP() []byte {
	file_task_service_proto_rawDescOnce.Do(func() {
		file_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)))
	})
	return file_task_service_proto_rawDescData
}

var file_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_task_service_proto_goTypes = []any{
	(*SendTaskRequest)(nil),    // 0: task.SendTaskRequest
	(*SendTaskResponse)(nil),   // 1: task.SendTaskResponse
	(*GetTasksRequest)(nil),    // 2: task.GetTasksRequest
	(*GetTasksResponse)(nil),   // 3: task.GetTasksResponse
	(*DeleteTaskRequest)(nil),  // 4: task.DeleteTaskRequest
	(*DeleteTaskResponse)(nil), // 5: task.DeleteTaskResponse
	(*ChangeTaskRequest)(nil),  // 6: task.ChangeTaskRequest
	(*ChangeTaskResponse)(nil), // 7: task.ChangeTaskResponse
	(*Task)(nil),               // 8: task.Task
	(*status.Status)(nil),      // 9: google.rpc.Status
}
var file_task_service_proto_depIdxs = []int32{
	8, // 0: task.SendTaskRequest.task:type_name -> task.Task
	9, // 1: task.SendTaskResponse.status:type_name -> google.rpc.Status
	8, // 2: task.GetTasksResponse.task:type_name -> task.Task
	9, // 3: task.DeleteTaskResponse.status:type_name -> google.rpc.Status
	9, // 4: task.ChangeTaskResponse.status:type_name -> google.rpc.Status
	0, // 5: task.TaskService.SendTask:input_type -> task.SendTaskRequest
	2, // 6: task.TaskService.GetTasks:input_type -> task.GetTasksRequest
	4, // 7: task.TaskService.DeleteTask:input_type -> task.DeleteTaskRequest
	6, // 8: task.TaskService.ChangeTask:input_type -> task.ChangeTaskRequest
	1, // 9: task.TaskService.SendTask:output_type -> task.SendTaskResponse
	3, // 10: task.TaskService.GetTasks:output_type -> task.GetTasksResponse
	5, // 11: task.TaskService.DeleteTask:output_type -> task.DeleteTaskResponse
	7, // 12: task.TaskService.ChangeTask:output_type -> task.ChangeTaskResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_task_service_proto_init() }
func file_task_service_proto_init() {
	if File_task_service_proto != nil {
		return
	}
	file_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_service_proto_goTypes,
		DependencyIndexes: file_task_service_proto_depIdxs,
		MessageInfos:      file_task_service_proto_msgTypes,
	}.Build()
	File_task_service_proto = out.File
	file_task_service_proto_goTypes = nil
	file_task_service_proto_depIdxs = nil
}
